### ISSUE TITLE
please make examples in docs less generic

### ISSUE THREAD

**Issue by alexhutko** [pnsn/squacapi_client#2]
https://github.com/pnsn/squacapi_client/blob/master/docs/V10Api.md#v1_0_nslc_channels_list

In the docs, some more specificity in the examples would be helpful. Current:

network = 'network_example' # str | Multiple values may be separated by commas. (optional)
channel = 'channel_example' # str | Multiple values may be separated by commas. (optional)
chan_search = 'chan_search_example' # str |  (optional)
station = 'station_example' # str | Multiple values may be separated by commas. (optional)
location = 'location_example' # str |  (optional)
startafter = 'startafter_example' # str |  (optional)

Would help to give some examples of say, how to wildcard:

network = 'UW' # str | Multiple values may be separated by commas. (optional)
channel = '??Z' # str | Multiple values may be separated by commas. (optional)
station = 'ALKI,GNW' # str | Multiple values may be separated by commas. (optional)
location = '*' # str |  (optional)
startafter = '2019-08-18T01:02:03' # str |  (optional)

I didn't see chan_search defined, so I don't know what that does.

**Comment by joncon** [comment]
This documentation is created automatically, I will do a better job with doc strings, which will add to this  documentation. The chan_search is an optional query param that takes a python regex, (case insensitive). 
example:
?chan_search=H(H|N). will find all hn* and hh*
?chan_search=..z would return all z chans
